name: Java CI - API & Web Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Pastikan gradlew bisa dieksekusi
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Jalankan API tests
      - name: Run API tests
        run: ./gradlew apiTest

      # 5. Jalankan Web tests
      - name: Run Web tests
        run: ./gradlew webTest

      # 6. Upload HTML report
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: build/reports/cucumber/*.html

      # 7. Upload JSON report
      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: build/reports/cucumber/*.json
