name: Run UI and API Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Chrome (for UI)
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libasound2 libxss1 libatk-bridge2.0-0 libgtk-3-0
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb || true

      - name: Run API tests
        run: ./gradlew runApiTests --no-daemon

      - name: Run Web tests
        run: |
          export DISPLAY=':99'
          Xvfb :99 -screen 0 1920x1080x24 & 
          ./gradlew runWebTests --no-daemon

      - name: Upload cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-reports
